### ISSUE TITLE
Generalize to MonadPrim

### ISSUE THREAD

**Issue by cocreature** [andrewthad/contiguous#1]
Currently all operations operate in `ST`. While it’s possible to lift that to `MonadPrim` using `stToPrim` that puts the burden on the user and clutters their codebase. Have you considered generalizing the operations to `MonadPrim`? I’d be happy to provide a pull request if that is all it takes.

**Comment by chessai** [comment]
I was thinking about doing the same myself the other day. I think this is fine. If you're available to make a PR for this that would be most helpful.
