### ISSUE TITLE
bounds against primitive

### ISSUE THREAD

**Issue by cartazio** [andrewthad/contiguous#25]
using my trustee hat i added a <0.7 bound to make sure its all good build wise.

**Comment by chessai** [comment]
awesome, thanks! Is this because of the UnliftedArray problems?

**Comment by cartazio** [comment]
and or removing Addr as was longed planned and such ..

**Comment by andrewthad** [comment]
It is. I have a primitive-unlifted package coming out later today that provides a different implementation of Data.Primitive.UnliftedArray that doesn’t lead to corruption when used with the FFI.

**Comment by cartazio** [comment]
i'm using https://github.com/hackage-trustees/hackage-cli to do my bulk edits, you can use it on the packages you have maintainer bit for on hackage if you like too

**Comment by chessai** [comment]
awesome, thanks @cartazio
