### ISSUE TITLE
Use primitive-unlifted

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/contiguous#26]
`Data.Primitive.UnliftedArray` has been removed in `primitive-0.7`. I have a more sound reimplementation in `primitive-unlifted`. We should use it instead.

**Comment by chessai** [comment]
When you release that package, do you think you could also make a release of contiguous that uses it?

**Comment by andrewthad** [comment]
PR is at https://github.com/andrewthad/contiguous/pull/27 if you'd like to look it over.

**Comment by chessai** [comment]
ok

**Comment by chessai** [comment]
released
