### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/contiguous#5]
I should really add some tests to this. Currently, most of the functions here are tested the tests in `primitive-containers` and `automata`, but I should really put tests in here too.

**Comment by chessai** [comment]
One thing we can do is write quickcheck-classes/hedgehog-classes `Laws` for testing contiguous. That way we could just use contiguousLaws for the four instances

**Comment by chessai** [comment]
i think this should be closed since there is a now a test suite, and any further issues about adding tests should be more specific about what we want to test
